# Default values for oidc-discovery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

config:
  apiServiceHost: kubernetes.default.svc.cluster.local
  apiServicePort: 443
  apiCaCert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  
  tls:
    enabled: false
    host: oidc.example.com
    expirationDays:
      ca: 1095 # default 3 years
      cert: 365 # default 1 year

image:
  repository: ghcr.io/atoy3731/k8s-oidc-discovery
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

# This securityContext is configured to run effectively with `restricted` PSA mode enabled.
securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: oidc.example.com

  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

