apiVersion: v1
kind: Service
metadata:
  name: {{ include "oidc-discovery.fullname" . }}
  labels:
    {{- include "oidc-discovery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.config.tls.enabled }}
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
    {{- else }}
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "oidc-discovery.selectorLabels" . | nindent 4 }}
