kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: k8s-oidc-discovery
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/k8s-oidc-discovery.git
  branch: kube-lol
  targets:
  - name: oidc
    clusterSelector:
      matchLabels:
        oidc: enabled
  paths:
  - "./fleet/cert-manager/cert-manager"
  - "./fleet/cert-manager/cert-resources"
  - "./fleet/istio/operator"
  - "./fleet/istio/istio-resources"
  - "./fleet/k8s-oidc-discovery"
  - "./fleet/eks-iam-webhook"
  - "./fleet/demo-app"