ingress:
  enabled: true
  host: oidc.kube.lol
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

ssl:
  enabled: true
  host: oidc.kube.lol