apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::539300447621:role/atoy-oidc-demo-role"
    eks.amazonaws.com/audience: "rke2"
