name: Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

env:
  IMAGE_NAME: atoy3731/rke2-oidc-discovery

jobs:
  docker-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      # Login: Log into Docker Hub using Github secrets.
      - name: Log into Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin

      - name: Prepare
        id: prep
        run: |
          VERSION=$(cat VERSION)

          TAGS="${IMAGE_NAME}:${VERSION},${IMAGE_NAME}:latest"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}

  helm-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.3.0
      with:
        name: rke2-oidc-discovery
        repository: atoy3731
        tag: 0.1.0
        path: "../../chart/"
        registry: registry-1.docker.io/atoy3731
        registry_username: ${{ secrets.DOCKER_USER }}
        registry_password: ${{ secrets.DOCKER_PASSWORD }}
        update_dependencies: 'true'