name: Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/ranchergovernment-sandbox/rke2-oidc-discovery

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag $IMAGE_NAME:0.1.0
        docker push $IMAGE_NAME:0.1.0

  helm-publish:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
    - uses: actions/checkout@v3
    
    - name: Push Helm chart to OCI compatible registry
      uses: bsord/helm-push@v4.1.0
      with:
        useOCIRegistry: true
        registry-url:  oci://ghcr.io/${{ secrets.REGISTRY_USER }}
        username: ${{ secrets.REGISTRY_USER }}
        access-token: ${{ secrets.REGISTRY_PASSWORD }}
        force: true
        chart-folder: chart