name: Docker

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Get Tag Name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> "$GITHUB_ENV"

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag $IMAGE_NAME:${{ env.TAG_NAME }}
        docker push $IMAGE_NAME:${{ env.TAG_NAME }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: Release ${{ env.TAG_NAME }}
        generate_release_notes: true

  helm-publish:
    runs-on: ubuntu-latest
    needs: docker-push
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"